### ISSUE TITLE
wayrs-core not published?

### ISSUE THREAD

**Issue by colinmarc** [MaxVerevkin/wayrs#11]
Hi, I'm interested in poking at wayrs-core, but I saw that it's not published to crates.io. Is it intentionally only for internal use or is that an oversight?

**Comment by MaxVerevkin** [comment]
It was extracted from `wayrs-client` just yesterday :) I will publish it soon, when I have some confidence that the API is good.

**Comment by colinmarc** [comment]
Oh cool 😅 are you planning on / would you be open to making wayrs-scanner useful for servers too? I have an idea for a compositor-side project and would love to use both.

**Comment by MaxVerevkin** [comment]
At this point I don't see how to make that possible. I have a toy Wayland compositor (https://github.com/MaxVerevkin/ewc) using `wayrs-core` (git version) and `wayrs-proto-parser`. But it has a custom "scanner" (a modified version of `wayrs-scanner`), which is specific to that project, because there is no standard generic server-side `Connection` type, so the scanner generates non-generic code. And it kinda has its upsides.

**Comment by MaxVerevkin** [comment]
@madushan1000 do you think `wayrs-core`'s current API is good enough?

**Comment by madushan1000** [comment]
maybe `ClientTransport` trait should be in it too? or is it more suited in `wayrs-client`?

**Comment by MaxVerevkin** [comment]
> maybe `ClientTransport` trait should be in it too?

No.

> maybe `ClientTransport` trait should be in it too? or is it more suited in `wayrs-client`?

Yes. Since it only makes sense for clients.

**Comment by madushan1000** [comment]
okay, then wayrs-core API is good enough for my work.

**Comment by MaxVerevkin** [comment]
The thing I'm not sure about is the `: AsRawFd` restriction of `Transport`. This for example prevents `impl Transport for Box<dyn Transport>`. Maybe `Transport::pollable_fd(&self) -> RawFd/BorrowedFd` is better.

**Comment by madushan1000** [comment]
Sounds good if that would make things more flexible.

**Comment by MaxVerevkin** [comment]
https://crates.io/crates/wayrs-core
